receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

connectors:
  spanmetrics:
    namespace: traces_spanmetrics
    histogram:
      explicit:
        buckets: [2ms, 6ms, 10ms, 25ms, 100ms, 250ms, 1s, 2.5s, 5s]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
        default: '200'
    metrics_flush_interval: 15s

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true
    metric_expiration: 5m

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
  telemetry:
    logs:
      level: info
